--liquibase formatted sql

--changeset codex-creator:001-initial-schema
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE provider_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    provider_type VARCHAR(40) NOT NULL,
    endpoint TEXT,
    secret_ref VARCHAR(256),
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE model_profiles (
    profile_id VARCHAR(128) PRIMARY KEY,
    provider_config_id BIGINT REFERENCES provider_configs(id) ON DELETE SET NULL,
    vendor VARCHAR(80) NOT NULL,
    model_id VARCHAR(160) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    reasoning_effort VARCHAR(32),
    capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
    allowed_operations JSONB NOT NULL DEFAULT '[]'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    discovered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE codex_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_thread_id VARCHAR(256) NOT NULL UNIQUE,
    profile_id VARCHAR(128) REFERENCES model_profiles(profile_id) ON DELETE SET NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    schema_version VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE automation_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR(80) NOT NULL,
    profile_id VARCHAR(128) REFERENCES model_profiles(profile_id) ON DELETE SET NULL,
    thread_id BIGINT REFERENCES codex_threads(id) ON DELETE SET NULL,
    idempotency_key VARCHAR(256) NOT NULL UNIQUE,
    trace_id VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    input JSONB NOT NULL,
    output JSONB,
    usage JSONB,
    provenance JSONB,
    error_code VARCHAR(80),
    error_message TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    next_attempt_at TIMESTAMPTZ
);

CREATE INDEX idx_automation_tasks_status ON automation_tasks(status, next_attempt_at, id);
CREATE INDEX idx_automation_tasks_trace ON automation_tasks(trace_id);

CREATE TABLE task_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES automation_tasks(id) ON DELETE CASCADE,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider VARCHAR(80),
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    usage JSONB,
    error_code VARCHAR(80),
    error_message TEXT,
    UNIQUE(task_id, attempt_number)
);

CREATE TABLE codex_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES automation_tasks(id) ON DELETE SET NULL,
    thread_id BIGINT REFERENCES codex_threads(id) ON DELETE SET NULL,
    external_turn_id VARCHAR(256),
    status VARCHAR(32) NOT NULL,
    input JSONB,
    output JSONB,
    error JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ
);

CREATE TABLE knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_uri TEXT,
    title TEXT NOT NULL,
    checksum VARCHAR(128) NOT NULL UNIQUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    ordinal INTEGER NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(document_id, ordinal)
);

CREATE TABLE vector_embeddings (
    chunk_id BIGINT PRIMARY KEY REFERENCES knowledge_chunks(id) ON DELETE CASCADE,
    embedding vector(1536) NOT NULL,
    model_id VARCHAR(160) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vector_embeddings_cosine ON vector_embeddings USING hnsw (embedding vector_cosine_ops);

CREATE TABLE ai_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    rationale TEXT,
    recommendation VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    source JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'SUGGESTED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ
);

CREATE TABLE ai_article_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES ai_topics(id) ON DELETE SET NULL,
    task_id BIGINT REFERENCES automation_tasks(id) ON DELETE SET NULL,
    target_category_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    auto_publish_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    policy_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    content JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(160),
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(80),
    resource_id VARCHAR(160),
    trace_id VARCHAR(160),
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE integration_nonces (
    nonce VARCHAR(160) PRIMARY KEY,
    client_id VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_integration_nonces_expiry ON integration_nonces(expires_at);

INSERT INTO provider_configs (name, provider_type, config)
VALUES ('codex-app-server', 'CODEX_APP_SERVER', '{"experimentalApi": false}'::jsonb)
ON CONFLICT (name) DO NOTHING;

INSERT INTO model_profiles (profile_id, vendor, model_id, display_name, reasoning_effort, capabilities, allowed_operations)
VALUES ('codex-default', 'OpenAI-Codex', 'auto', 'OpenAI-Codex-auto', 'low',
        '{"text": true, "structuredOutput": true, "stream": true}'::jsonb,
        '["summarize", "moderate", "translate", "slug", "assistant", "topic"]'::jsonb)
ON CONFLICT (profile_id) DO NOTHING;

--rollback DROP TABLE integration_nonces;
--rollback DROP TABLE audit_logs;
--rollback DROP TABLE ai_article_jobs;
--rollback DROP TABLE ai_topics;
--rollback DROP INDEX idx_vector_embeddings_cosine;
--rollback DROP TABLE vector_embeddings;
--rollback DROP TABLE knowledge_chunks;
--rollback DROP TABLE knowledge_documents;
--rollback DROP TABLE codex_turns;
--rollback DROP TABLE task_attempts;
--rollback DROP TABLE automation_tasks;
--rollback DROP TABLE codex_threads;
--rollback DROP TABLE model_profiles;
--rollback DROP TABLE provider_configs;
