--liquibase formatted sql

--changeset codex-creator:002-topic-automation
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE topic_automation_settings (
    id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    interval_minutes INTEGER NOT NULL DEFAULT 360,
    max_seeds_per_run INTEGER NOT NULL DEFAULT 5,
    max_topics_per_run INTEGER NOT NULL DEFAULT 20,
    next_run_at TIMESTAMPTZ,
    last_run_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_topic_interval_minutes CHECK (interval_minutes BETWEEN 60 AND 1440),
    CONSTRAINT chk_topic_max_seeds CHECK (max_seeds_per_run BETWEEN 1 AND 20),
    CONSTRAINT chk_topic_max_topics CHECK (max_topics_per_run BETWEEN 1 AND 50)
);

INSERT INTO topic_automation_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

UPDATE model_profiles
SET allowed_operations = allowed_operations || '["article"]'::jsonb,
    updated_at = CURRENT_TIMESTAMP
WHERE profile_id = 'codex-default'
  AND NOT (allowed_operations @> '["article"]'::jsonb);

CREATE TABLE topic_query_seeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    query TEXT NOT NULL,
    language VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
    region VARCHAR(64),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_topic_query_seeds_enabled ON topic_query_seeds(enabled, sort_order, last_used_at, id);

CREATE TABLE topic_discovery_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    task_id BIGINT REFERENCES automation_tasks(id) ON DELETE SET NULL,
    idempotency_key VARCHAR(256) NOT NULL UNIQUE,
    trace_id VARCHAR(160) NOT NULL,
    seed_count INTEGER NOT NULL DEFAULT 0,
    seed_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
    topic_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE INDEX idx_topic_discovery_runs_status ON topic_discovery_runs(status, created_at DESC);

ALTER TABLE ai_topics ADD COLUMN dedupe_key VARCHAR(64);
ALTER TABLE ai_topics ADD COLUMN discovery_run_id BIGINT REFERENCES topic_discovery_runs(id) ON DELETE SET NULL;
ALTER TABLE ai_topics ADD COLUMN last_seen_at TIMESTAMPTZ;
ALTER TABLE ai_topics ADD COLUMN occurrence_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_topics ADD COLUMN review_note TEXT;
ALTER TABLE ai_topics ADD COLUMN updated_at TIMESTAMPTZ;

UPDATE ai_topics
SET dedupe_key = encode(digest(lower(regexp_replace(trim(title), '\s+', ' ', 'g')), 'sha256'), 'hex'),
    last_seen_at = created_at,
    updated_at = created_at
WHERE dedupe_key IS NULL;

-- Preserve existing duplicate rows without losing them. New discoveries use the
-- canonical title hash and will merge into the first row in each legacy group.
WITH duplicate_rows AS (
    SELECT id, row_number() OVER (PARTITION BY dedupe_key ORDER BY id) AS row_number
    FROM ai_topics
)
UPDATE ai_topics topic
SET dedupe_key = encode(digest(topic.dedupe_key || ':' || topic.id, 'sha256'), 'hex')
FROM duplicate_rows duplicate_row
WHERE topic.id = duplicate_row.id
  AND duplicate_row.row_number > 1;

ALTER TABLE ai_topics ALTER COLUMN dedupe_key SET NOT NULL;
ALTER TABLE ai_topics ALTER COLUMN last_seen_at SET NOT NULL;
ALTER TABLE ai_topics ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE ai_topics ADD CONSTRAINT uq_ai_topics_dedupe_key UNIQUE (dedupe_key);
CREATE INDEX idx_ai_topics_status_seen ON ai_topics(status, last_seen_at DESC, id DESC);

ALTER TABLE ai_article_jobs ADD COLUMN request_key VARCHAR(256);
ALTER TABLE ai_article_jobs ADD COLUMN language VARCHAR(16) NOT NULL DEFAULT 'zh-CN';
ALTER TABLE ai_article_jobs ADD COLUMN instructions TEXT;
ALTER TABLE ai_article_jobs ADD COLUMN windblog_post_id BIGINT;
ALTER TABLE ai_article_jobs ADD COLUMN provenance JSONB;
ALTER TABLE ai_article_jobs ADD COLUMN error_message TEXT;
ALTER TABLE ai_article_jobs ADD COLUMN updated_at TIMESTAMPTZ;
ALTER TABLE ai_article_jobs ADD COLUMN completed_at TIMESTAMPTZ;

UPDATE ai_article_jobs
SET request_key = 'legacy-article-job-' || id,
    updated_at = created_at
WHERE request_key IS NULL;

ALTER TABLE ai_article_jobs ALTER COLUMN request_key SET NOT NULL;
ALTER TABLE ai_article_jobs ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE ai_article_jobs ADD CONSTRAINT uq_ai_article_jobs_request_key UNIQUE (request_key);
CREATE INDEX idx_ai_article_jobs_status ON ai_article_jobs(status, updated_at DESC, id DESC);

--rollback DROP INDEX idx_ai_article_jobs_status;
--rollback ALTER TABLE ai_article_jobs DROP CONSTRAINT uq_ai_article_jobs_request_key;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN completed_at;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN updated_at;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN error_message;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN provenance;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN windblog_post_id;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN instructions;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN language;
--rollback ALTER TABLE ai_article_jobs DROP COLUMN request_key;
--rollback DROP INDEX idx_ai_topics_status_seen;
--rollback ALTER TABLE ai_topics DROP CONSTRAINT uq_ai_topics_dedupe_key;
--rollback ALTER TABLE ai_topics DROP COLUMN updated_at;
--rollback ALTER TABLE ai_topics DROP COLUMN review_note;
--rollback ALTER TABLE ai_topics DROP COLUMN occurrence_count;
--rollback ALTER TABLE ai_topics DROP COLUMN last_seen_at;
--rollback ALTER TABLE ai_topics DROP COLUMN discovery_run_id;
--rollback ALTER TABLE ai_topics DROP COLUMN dedupe_key;
--rollback DROP INDEX idx_topic_discovery_runs_status;
--rollback DROP TABLE topic_discovery_runs;
--rollback DROP INDEX idx_topic_query_seeds_enabled;
--rollback DROP TABLE topic_query_seeds;
--rollback DROP TABLE topic_automation_settings;
