--liquibase formatted sql

--changeset codex-creator:006-test-servers
CREATE TABLE test_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    host VARCHAR(255) NOT NULL,
    ssh_port INTEGER NOT NULL DEFAULT 22,
    ssh_user VARCHAR(64) NOT NULL DEFAULT 'root',
    private_key_encrypted TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ai_article_job_test_servers (
    article_job_id BIGINT NOT NULL REFERENCES ai_article_jobs(id) ON DELETE CASCADE,
    test_server_id BIGINT NOT NULL REFERENCES test_servers(id) ON DELETE RESTRICT,
    PRIMARY KEY (article_job_id, test_server_id)
);
ALTER TABLE ai_article_jobs ADD COLUMN requires_practical_verification BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE model_profiles
SET allowed_operations = allowed_operations || '["test-server.execute"]'::jsonb
WHERE profile_id = 'codex-default'
  AND NOT (allowed_operations @> '["test-server.execute"]'::jsonb);

--rollback DROP TABLE ai_article_job_test_servers;
--rollback DROP TABLE test_servers;
