--liquibase formatted sql

--changeset codex-creator:009-article-job-evidence
CREATE TABLE ai_article_job_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_job_id BIGINT NOT NULL REFERENCES ai_article_jobs(id) ON DELETE CASCADE,
    generation_attempt INTEGER NOT NULL,
    kind VARCHAR(32) NOT NULL,
    media_url VARCHAR(2048),
    server_id BIGINT,
    command TEXT,
    exit_code INTEGER,
    output TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ai_article_job_evidence_kind CHECK (kind IN ('IMAGE', 'VERIFICATION'))
);
CREATE INDEX idx_ai_article_job_evidence_attempt
    ON ai_article_job_evidence(article_job_id, generation_attempt, kind, id);

--rollback DROP TABLE ai_article_job_evidence;
